server:
  port: 8085

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pathfinder
      grid-fs-database: pathfinder-gridfs
      
 
  main:
      sources: za.co.yellowfire.threesixty.PathfinderApplication

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO


