server:
  port: 8085

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: pathfinder
      password: pathfinder
      database: pathfinder
      grid-fs-database: pathfinder-gridfs
  main:
      sources: za.co.yellowfire.pathfinder.PathfinderApplication

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO


